[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
notify = "6.1"
ignore = "0.4"
tree-sitter = "0.20"
tree-sitter-python = "0.20"